
SPAM_KEYWORDS = [

    # OTP / Banking Fraud
    "otp",
    "share otp",
    "bank account",
    "credit card",
    "debit card",
    "cvv",
    "upi pin",
    "upi",
    "atm pin",
    "net banking",
    "verify account",
    "account verification",
    "bank verification",
    "bank details",
    "customer id",
    "password",
    "transaction failed",
    "unauthorized transaction",
    "suspicious activity",
    "account blocked",
    "your account will be blocked",
    "payment arrangement",

    # Financial Scam
    "loan approved",
    "instant loan",
    "pre approved loan",
    "easy emi",
    "zero interest",
    "credit limit increase",
    "income tax refund",
    "tax refund",
    "investment scheme",
    "bitcoin investment",
    "crypto investment",
    "double your money",
    "high return investment",
    "guaranteed profit",
    "quick income",
    "earn money quickly",
    "part time income",
    "work from home income",
    "passive income",
    "financial freedom",

    # Urgency / Pressure
    "urgent action",
    "act immediately",
    "limited time offer",
    "offer expires today",
    "do it now",
    "last warning",
    "final notice",
    "immediate response required",
    "respond immediately",
    "legal action",
    "account suspended",
    "security alert",
    "payment pending",
    "payment overdue",
    "verification required",
    "kyc pending",
    "kyc update required",
    "update immediately",
    "deadline today",
    "time sensitive",

    # Fake Rewards / Lottery
    "free gift",
    "claim reward",
    "claim your cashback",
    "lottery",
    "prize money",
    "congratulations you won",
    "winner selected",
    "cash prize",
    "gift voucher",
    "exclusive reward",
    "special reward",
    "reward points",
    "free iphone",
    "free vacation",
    "lucky winner",
    "spin and win",
    "mega offer",
    "bonus reward",
    "free recharge",
    "claim now",

    # Phishing / Tech Scam
    "click this link",
    "download this app",
    "install app",
    "remote access",
    "screen sharing",
    "verify your identity",
    "identity verification",
    "login immediately",
    "reset password",
    "security update",
    "system hacked",
    "device infected",
    "virus detected",
    "malware detected",
    "technical support",
    "customer support",
    "support executive",
    "update app",
    "confirm details",
    "submit details",

    # Aggressive Sales / Marketing
    "buy now",
    "special discount",
    "exclusive deal",
    "limited seats",
    "lowest price",
    "best deal",
    "massive savings",
    "exclusive access",
    "premium membership",
    "subscription renewal",
    "free trial",
    "auto renewal",
    "cancel subscription",
    "membership expired",
    "insurance offer",
    "health insurance",
    "car insurance",
    "life insurance",
    "upgrade plan",
    "exclusive package",
    "offer",
    "offer just for you",
    "gift card",
    "prize",
    "is scam",
    "scam",
    "debit",
    "credit",
    "bank",
    "account",
    "check"
]
